# Generated by Django 4.1.6 on 2023-02-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('authority', models.CharField(choices=[('P', 'President'), ('Vp', 'Vice_President'), ('S', 'Secretary'), ('Fs', 'Financial_Secretary'), ('T', 'Treasurer'), ('Ss', 'Social Secretary'), ('Cw', 'Chief Whip')], max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField(blank=True)),
                ('monthofbenefit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavingTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('C', 'Cashout')], max_length=1)),
                ('deposit_amount', models.IntegerField()),
                ('deposit_date', models.DateField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapps.newmember')),
            ],
        ),
        migrations.CreateModel(
            name='MonthContrib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_contribution', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapps.newmember')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanamount', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
                ('remarks', models.TextField(max_length=500)),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapps.newmember')),
            ],
        ),
    ]
