# Generated by Django 4.1.6 on 2023-04-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='authority',
            field=models.CharField(choices=[('P', 'President'), ('Vp', 'Vice_President'), ('S', 'Secretary'), ('Fs', 'Financial_Secretary'), ('T', 'Treasurer'), ('Ss', 'Social Secretary'), ('Cw', 'Chief Whip'), ('M', 'Member')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='monthofbenefit',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savingtab',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Cashout', 'Cashout')], max_length=8),
        ),
    ]
